2025-10-06 10:08:32.045 [info] 




2025-10-06 10:08:32.081 [info] Extension host agent started.
2025-10-06 10:08:32.196 [info] Started initializing default profile extensions in extensions installation folder. file:///home/pi/.vscode-server/extensions
2025-10-06 10:08:32.315 [info] [<unknown>][d0893879][ManagementConnection] New connection established.
2025-10-06 10:08:32.320 [info] [<unknown>][6c8b8ea4][ExtensionHostConnection] New connection established.
2025-10-06 10:08:32.350 [info] Completed initializing default profile extensions in extensions installation folder. file:///home/pi/.vscode-server/extensions
2025-10-06 10:08:32.506 [info] [<unknown>][6c8b8ea4][ExtensionHostConnection] <3073> Launched Extension Host Process.
2025-10-06 10:08:35.912 [error] CodeExpectedError: Could not find pty 4 on pty host
    at I.W (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:46:6451)
    at I.updateTitle (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:46:1839)
    at s.<computed> (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:45:2938)
    at Object.call (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at vl.s (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:81574)
    at vl.q (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:81097)
    at ps.value (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80499)
    at E.C (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at E.fire (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2591)
    at process.C (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:24:30159)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:949:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
2025-10-06 10:08:35.918 [error] CodeExpectedError: Could not find pty 4 on pty host
    at I.W (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:46:6451)
    at I.updateIcon (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:46:1889)
    at s.<computed> (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:45:2938)
    at Object.call (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at vl.s (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:81574)
    at vl.q (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:81097)
    at ps.value (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80499)
    at E.C (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at E.fire (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2591)
    at process.C (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:24:30159)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:949:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
2025-10-06 10:08:41.585 [info] [<unknown>][d0893879][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
2025-10-06 10:08:41.660 [info] [<unknown>][6c8b8ea4][ExtensionHostConnection] <3073> Extension Host Process exited with code: 0, signal: null.
2025-10-06 10:08:41.662 [info] Cancelling previous shutdown timeout
2025-10-06 10:08:41.662 [info] Last EH closed, waiting before shutting down
2025-10-06 10:08:46.355 [info] [<unknown>][64cbef90][ExtensionHostConnection] New connection established.
2025-10-06 10:08:46.364 [info] [<unknown>][64cbef90][ExtensionHostConnection] <3178> Launched Extension Host Process.
2025-10-06 10:08:46.402 [info] [<unknown>][0bf0e06b][ManagementConnection] New connection established.
2025-10-06 10:08:48.488 [error] CodeExpectedError: Could not find pty 2 on pty host
    at I.W (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:46:6451)
    at I.updateTitle (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:46:1839)
    at s.<computed> (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:45:2938)
    at Object.call (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:28:4204)
    at vl.s (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:81574)
    at vl.q (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:81097)
    at ps.value (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:80499)
    at E.C (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2373)
    at E.fire (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:26:2591)
    at process.C (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/vs/platform/terminal/node/ptyHostMain.js:24:30159)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:949:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:91:21)
2025-10-06 10:13:41.667 [info] New EH opened, aborting shutdown
2025-10-06 10:13:41.675 [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (file:///home/pi/.vscode-server/cli/servers/Stable-6f17636121051a53c88d3e605c491d22af2ba755/server/out/server-main.js:184:1060)
    at process.emit (node:events:530:35)
2025-10-06 10:38:42.375 [info] [<unknown>][0bf0e06b][ManagementConnection] The client has disconnected, will wait for reconnection 3h before disposing...
